apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-{{ env "environment" }}
spec:
  serviceName: {{ .Chart.Name }}-{{ env "environment" }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ env "environment" }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ env "environment" }}
    spec:
      containers:
      - name: nginx
        {{ tuple (printf "nginx") . | werf_container_image }}
        lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - "wget https://raw.githubusercontent.com/zhdanov/films/main/films.html -O /usr/share/nginx/html/index.html"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
